package com.university.attendance.models;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents one QR attendance session generated by a teacher.
 * Maps to the 'attendance_sessions' table.
 *
 * When a teacher clicks "Generate QR", a new session is created with:
 * - A fresh UUID v4 qr_token (what the QR image encodes)
 * - generated_at = NOW()
 * - expires_at = generated_at + QR_EXPIRY_SECONDS
 * - is_active = true
 *
 * After expiry, the @Scheduled background job sets is_active = false
 * and inserts ABSENT records for students who didn't scan.
 *
 * Denormalized fields (teacher_id, subject_id, semester_id) are
 * intentionally repeated from the allocation chain for fast report queries.
 */
@Entity
@Table(name = "attendance_sessions")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AttendanceSession {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "session_id", updatable = false, nullable = false)
    private UUID sessionId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "allocation_id", nullable = false)
    private TeacherSubjectAllocation allocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "slot_id")
    private TimetableSlot slot;

    // ── Denormalized fields for fast report queries ──

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "teacher_id", nullable = false)
    private Teacher teacher;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "semester_id", nullable = false)
    private Semester semester;

    // ── Session data ──

    @Column(name = "session_date", nullable = false)
    private LocalDate sessionDate;

    @Column(name = "qr_token", length = 36, nullable = false, unique = true)
    private String qrToken;

    @Column(name = "generated_at", nullable = false)
    private LocalDateTime generatedAt;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Builder.Default
    @Column(name = "is_active", nullable = false)
    private Boolean isActive = true;
}
